# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 5.0.0

app:
  image: mageinferno/magento2-nginx:1.11-0
  container_name: hooks_app
  links:
    - phpfpm
    - db
    - phpmyadmin

  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  container_name: hooks_app_data
  volumes:
    - /var/www/html
    - ~/.composer:/var/www/.composer
# Copying the entire contents of the appdata data volume to your local machine.
# >>> docker cp CONTAINERID:/var/www/html ./html
# Then, just uncomment below lines
    - ./html/app/code:/var/www/html/app/code 
    - ./html/app/design:/var/www/html/app/design
    - ./html/.htaccess:/var/www/html/.htaccess
    - ./html/package.json:/var/www/html/package.json
    - ./html/Gruntfile.js:/var/www/html/Gruntfile.js
    - ./html/dev/tools/grunt/configs/themes.js:/var/www/html/dev/tools/grunt/configs/themes.js

phpfpm:
  image: mageinferno/magento2-php:7.0-fpm-0
  container_name: hooks_php_fpm
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  container_name: hooks_db
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=hooksdb
    - MYSQL_USER=hookuser
    - MYSQL_PASSWORD=hook321*#

dbdata:
  image: tianon/true
  container_name: hooks_db_data
  volumes:
    - /var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: hooks_phpmyadmin
  ports:
    - "8580:80"
  links:
    - db   

node:
  build: ./docker/node
  container_name: hooks_node
  volumes_from:
    - appdata
  links:
    - phpfpm 
  ports:
    - 8120:80

# https://github.com/joshporter/magento2-docker
# docker-compose run --rm node npm install -g grunt-cli
# docker-compose run --rm node npm install
# docker-compose run --rm node grunt <task>

# Run command in stopped container - docker-compose run --rm node bash


setup:
  image: mageinferno/magento2-php:7.0-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=hooksdb
    - M2SETUP_DB_USER=hookuser
    - M2SETUP_DB_PASSWORD=hook321*#
    - M2SETUP_BASE_URL=http://m2.localhost:8000/
    - M2SETUP_ADMIN_FIRSTNAME=manoj 
    - M2SETUP_ADMIN_LASTNAME=kumar
    - M2SETUP_ADMIN_EMAIL=tvmmanu@gmail.com
    - M2SETUP_ADMIN_USER=hooks
    - M2SETUP_ADMIN_PASSWORD=hooksadmin312*#
    - M2SETUP_VERSION=2.1.2
    - M2SETUP_USE_SAMPLE_DATA=true
    - M2SETUP_USE_ARCHIVE=false
    - M2SETUP_USE_COMPOSER_ENTERPRISE=false
